---
title: "Integrering af kort fra din forening"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For at kortlag fra din forening kan tilføjes, er det nødvendigt at du inddeler dig Google kort i forskellige lag. Det kan nemt gøres under [my maps](https://www.google.com/maps/d/u/0/) og kræver generelt ikke de store ændringer. Du tilføjer lag ved at klikke på *Add layers* øverst til venstre når du redigerer dit kort.

Indel dit Google map i lag (layers) med navne indeholdende

* Fiskevand (vises med blåt): Linjer i åen der indikerer fiskevand, hvor fiskeretten haves på mindst en af siderne. 
* Dagkort (vises med sort): Linjer der indikerer dagkortvand.
* Medlem (vises med gult): Linjer der indikerer medlemsvand (kun for medlemmer).
* Gæstekort (vises med rødt): Linjer der indikerer gæstekortvand.
* Sten (*rock* icon): Markeringer af sten.
* Parkering (*parkering* icon): Markeringer og linjer (tilkørselsveje) omhandlende parkering.
* Bro (*bridge* icon): Markeringer af broer.
* Spang (*footbridge* icon): Markeringer af spang.
* Shelter (*shelter* icon): Markeringer af shelter.
* Standpladser (*fish* icon): Markeringer af standpladser (dog ikke sten).
* Info: Markeringer og linjer der ikke hører under ovenstående (her forsøges at gætte icon der skal bruges). Der er ingen garanti for at alle inkluderes.