---
title: "Fangst analyse af MV-LFs strækninger"
author: "Lars Relund Nielsen"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: true
    theme: united
    highlight: tango
    df_print: paged
    # code_folding: show
    # toc: true
    # toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(lubridate)
library(DT)
# library(zoo) 
library(jsonlite)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning=FALSE, message=FALSE, 
  include = TRUE, echo = FALSE, 
  cache = FALSE, autodep = TRUE,
  out.width = "99%", fig.width = 8, fig.align = "center", fig.asp = 0.62
)

```


## Karup Å

```{r}
library(rvest)
url <- "https://fangstjournalen.dtu.dk/fangst.nsf/extEntry.xsp?open&club=37E6FB0707BAE0A1C1257F3A003FF013"
page <- read_html(url)
tmp <- page %>%
  html_elements(xpath = '//*[@id="view:_id1:inputClubLocation"]') %>% 
  html_elements("option") %>% 
  html_text() 
tmp <- unique(tmp[tmp != ""])
river <- str_extract(tmp, "^.*\\((.*)\\)$", group = 1)
river[is.na(river)] <- tmp[is.na(river)]
place <- str_extract(tmp, "^(.*)\\((.*)\\)$", group = 1) %>% 
  str_trim()
place[is.na(place)] <- tmp[is.na(place)]
datPlaces <- tibble(River = river, Place = place)
```



```{r}
urlFileExist <- function(url){
  HTTP_STATUS_OK <- 200
  hd <- httr::HEAD(url)
  status <- hd$all_headers[[1]]$status
  lst <- list(exists = status == HTTP_STATUS_OK, status = status)
  return(lst$exists)
}

prefix <- "https://raw.githubusercontent.com/relund/riverdata/master/data/data_mv-lf"
yr <- year(now())
datCatch <- NULL
for (y in 2016:yr) {
  fn <- paste0(prefix, "_catch_all_", y, ".csv")
  if (urlFileExist(fn)) datCatch <- bind_rows(datCatch, read_csv(fn, col_types = "Tfd"))
}
datCatch <- datCatch %>% 
  mutate(Year = year(Date))
datCatch <- datCatch %>% 
  filter(Species %in% c("Havørred", "Laks", "Bækørred", "Stalling", "Aborre", "Gedde", "Ål")) %>% 
  filter(!(River == "Skjern Å" & is.na(Place))) %>% 
  filter(!(River == "Karup Å" & is.na(Place))) %>% 
  mutate(Place = if_else(is.na(Place), River, Place))
# datCatch %>% filter(is.na(Place))

dat <- datCatch %>% 
  count(River, Place, Year) %>% 
  full_join(datPlaces) %>% 
  replace_na(list(Year = 2023, n = 0))
# View(dat)

dat %>% 
  pivot_wider(names_from = Year, values_from = n, names_sort = T) %>% 
  rowwise(River, Place) %>% 
  mutate(Middel = rowMeans(pick(where(is.numeric)), na.rm = T))
```

