---
output: html_document
title: "Oversigt over MV-LFs fiskevande"
editor_options: 
  chunk_output_type: console
# knit: (function(inputFile, encoding) { 
#       out_dir <- '../docs/mv-lf';
#       rmarkdown::render(inputFile,
#                         encoding=encoding, 
#                         output_file=file.path(dirname(inputFile), out_dir, 'mv-lf-kort.html')) })
---

<!-- File for generating the interactive map for MV-LF (run by GitHub Actions every hour) -->
<!-- Output is a html file in docs/mv-lf. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# library(htmltools)
# library(tidyverse)
# library(leaflet)
# library(leaflet.extras)
library(riverdata)
```

<style>
  body {
      padding: 0 !important;
      margin: 0 !important;
  }
  .main-container {
    max-width: 4000px
  }
  .container-fluid {
      padding: 0 !important;
  }
  #header {
      display: none;
  }
</style>

```{r}
prefix <- "../../data/data_mv-lf_"
snip_leaflet(prefix, show_groups = c("Parkering", "Bro/spang", "Info", "MV-LF (fiskevand)", "MV-LF (medlem)", "MV-LF (dagkort)"))
```
