---
title: "Karup Å - Vandstand"
author: ''
output:
  flexdashboard::flex_dashboard:
    css: www/style.css
    favicon: favicon.png
    orientation: rows
    theme: paper
    vertical_layout: fill
# knit: (function(inputFile, encoding) { 
#       rmarkdown::render(inputFile,
editor_options:
  chunk_output_type: console
---

<script>
$(".selectize-input input").prop('readonly','readonly');
</script>

```{r, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
library(plotly)
library(flexdashboard)
library(tidyverse)
library(conflicted)
conflicts_prefer(
  plotly::layout,
  dplyr::filter
  )

here::i_am("reports/karup/karup-waterlevel.Rmd")
source(here::here("reports/functions.R"))
Sys.setlocale("LC_ALL", "da_DK.UTF-8")

prefix <- "https://raw.githubusercontent.com/relund/riverdata/master/data/"
prefix <- "../../data/"
# Water levels
dat <- read_csv(paste0(prefix, "data_karup_waterlevel_web.csv"),
           locale = locale(tz = "CET"),
           col_types = "Tffdd") 
dat$YGroup <- factor(dat$YGroup, level = str_sort(levels(dat$YGroup)))
dat1 <- dat %>% 
  select(-Level) %>% 
  pivot_wider(names_from = Place, values_from = LevelRelative)
```

```{r}
plotPlaceRel <- function(place) {
  tmp <- dat1 %>% 
    transmute(Dato = Date, YGroup, Place = .data[[place]], 
              Text = str_c(day(Date), " ", month(Date, label = T), " ", YGroup, ": ", Place, " cm"),
              Width = if_else(YGroup == year(now()), "d", "g")) %>% 
    filter(!is.na(Place))
  fig <- plot_ly(tmp, type = 'scatter', mode = 'lines') %>% 
    add_lines(x = ~Dato, y = ~Place, split = ~YGroup, color = ~YGroup, 
              text = ~Text, 
              line = list(width = 1),
              hovertemplate = str_c('%{text}'),
              data = tmp, visible = T) %>% 
    layout(
      # title = place,
      xaxis = list(domain = c(0, 1), title = NA, tickformat = "%d %b"),
      yaxis = list(title = NA),
      legend = list(orientation = 'h')
      # hovermode = "x unified"
  )
  return(fig)
}
```

Hagebro
=======================================================================

Row
-----------------------------------------------------------------------

### Hagebro

```{r}
plotPlaceRel("Hagebro")
```



Karup By 
=======================================================================

Row
-----------------------------------------------------------------------

### Karup By 

```{r}
plotPlaceRel("Karup By")
```


Nørkærbro
=======================================================================

Row
-----------------------------------------------------------------------

### Nørkærbro

```{r}
plotPlaceRel("Nørkærbro")
```

