---
title: "Skjern Å - Fangster"
author: ''
output:
  flexdashboard::flex_dashboard:
    css: www/style.css
    favicon: favicon.png
    orientation: rows
    theme: paper
    vertical_layout: fill
# knit: (function(inputFile, encoding) { 
#       rmarkdown::render(inputFile,
editor_options:
  chunk_output_type: console
---

<script>
$(".selectize-input input").prop('readonly','readonly');
</script>

```{r, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
#library(ggrepel)
# library(directlabels)
library(plotly)
library(flexdashboard)
library(tidyverse)



# library(formattable)
# library(flextable)
library(kableExtra)
# library(zoo)
# library(leaflet)
# library(fs)
library(htmltools)

# library(knitr)
# knitr::opts_chunk$set(echo = FALSE)
# library(ggplot2)
# #library(ggrepel)
# library(directlabels)
# library(plotly)
# library(flexdashboard)
# library(tidyverse)
# library(lubridate)
# library(shiny)
# library(DT)
# # library(formattable)
# library(flextable)
# library(shinyBS)
# library(kableExtra)
# # library(zoo) 
# library(leaflet)
# library(fs)



source("../functions.R")

prefix <- "https://raw.githubusercontent.com/relund/riverdata/master/data/"
# prefix <- "../../data/"
curYear <- if_else(month(now())*100 + day(now()) < 416, year(now())-1, year(now()))   # assume previous year until season starts

# Weight - Estimates 
datWeightSea<- read_csv(paste0(prefix, "data_skjern_weight_seatrout.csv"), col_types = "dfddd")
datWeightSal <- read_csv(paste0(prefix, "data_skjern_weight_salmon.csv"), col_types = "dfddd")

# Catch - Records 
datCatchSal <- readCatch(paste0(prefix, "data_skjern_catch_salmon"), datWeightSal)
datCatchSea <- readCatch(paste0(prefix, "data_skjern_catch_seatrout"), datWeightSea)

# Catch - Yearly statistics
datStatYearSal <- yearlyStat(datCatchSal)
datStatYearSea <- yearlyStat(datCatchSea)

# Catch - Monthly statistics
datStatMonthSal <- monthlyStat(datCatchSal, curYear)
datStatMonthSea <- monthlyStat(datCatchSea, curYear)
```

```{r}
faIcon <- function (name, class = "", title = "", lib = "font-awesome") 
{
    prefixes <- list(`font-awesome` = "fa", glyphicon = "glyphicon")
    prefix <- prefixes[[lib]]
    if (is.null(prefix)) {
        stop("Unknown font library '", lib, "' specified. Must be one of ", 
            paste0("\"", names(prefixes), "\"", collapse = ", "))
    }
    if (class != "") class = paste0(" ", class)
    prefix_class <- prefix
    if (prefix_class == "fa") prefix_class <- "fas"
    iconClass <- paste0(prefix_class, " ", prefix, "-", name, class)
    iconTag <- tags$i(class = iconClass, title = title)
    htmltools::htmlDependencies(iconTag) <- htmltools::htmlDependency("font-awesome", 
        "5.3.1", "www/shared/fontawesome", package = "shiny", 
        stylesheet = c("css/all.min.css", "css/v4-shims.min.css"))
    htmltools::browsable(iconTag)
}
# addResourcePath('www', paste0(getwd(), "/www"))
```



Fangster `r curYear` {data-navmenu="Laks" #fangster-sal}
=======================================================================
  
Row
-----------------------------------------------------------------------
  
### Fangster den seneste måned
  
```{r}
  dat <- datCatchSal %>% 
    dplyr::filter(Date > now(tzone = "CET") - days(30)) %>% 
    select(Date, Place) %>% 
    arrange(desc(Date))

  ggplot(data = dat, aes(x = Date)) +
    geom_bar(aes(fill = Place), width = 0.75) + 
    geom_text(aes(label = after_stat(count), y= after_stat(count) ), stat= "count", position = position_dodge(width = 1)) + #  vjust = -0.5
    scale_x_date(date_labels = "%e. %b", date_breaks = "1 day", limits = c(NA_Date_, date(now()+ddays(1)))) + # now()+ddays(1)
    labs(fill = "") + xlab("Dato") + ylab("Antal fangster") + 
    theme(axis.text.x  = element_text(angle=45, hjust = 1, vjust = 1), legend.position="bottom")
```

Row
-----------------------------------------------------------------------

### Ugentlige fangster `r curYear`

```{r}
dat <- datCatchSal %>% 
  dplyr::filter(Date > ymd(paste0(curYear,"-01-01"))) %>% 
  select(Week, Place)

p <- ggplot(data = dat, aes(x = Week)) +
  geom_bar(aes(fill = Place)) + 
  geom_text(aes(label = after_stat(count), y= after_stat(count) ), stat= "count", position = position_dodge(width = 1)) #  vjust = -0.5
if (curYear == year(now())) p <- p + expand_limits(x = isoweek(now())) 
p <- p +
  coord_cartesian(clip = 'off') +
  labs(fill = "") + xlab("Uge") + ylab("Antal fangster") + 
  theme(axis.text.x  = element_text(angle=45, hjust = 1, vjust = 1), legend.position="bottom")
ggplotly(p) %>% 
    layout(
      # title = place,
      # xaxis = list(domain = c(0, 1), title = NA, tickformat = "%d %b"),
      # yaxis = list(title = "Relativ vandstand"),
      legend = list(orientation = 'h')
      # hovermode = "x unified"
  )
```


### Månedlige fangster `r curYear`

```{r}
dat <- datCatchSal %>% 
  dplyr::filter(Date > ymd(paste0(curYear,"-01-01"))) %>% 
  select(Month, Place)

p <- ggplot(dat, aes(x = Month)) + 
  geom_bar(aes(fill = Place)) + 
  geom_text(aes(label = after_stat(count), y= after_stat(count) ), stat= "count", position = position_dodge(width = 1)) # vjust = -.5 
# if (curYear == year(now())) p <- p + expand_limits(x = isoweek(now())) 
p <- p +
  coord_cartesian(clip = 'off') +
  labs(fill = "") + xlab("Måned") + ylab("Antal fangster") + 
  theme(axis.text.x  = element_text(angle=45, hjust = 1, vjust = 1), legend.position="bottom")
ggplotly(p) %>% 
    layout(
      # title = place,
      # xaxis = list(domain = c(0, 1), title = NA, tickformat = "%d %b"),
      # yaxis = list(title = "Relativ vandstand"),
      legend = list(orientation = 'h')
      # hovermode = "x unified"
  )
```


Row
-----------------------------------------------------------------------

### Opsumering

```{r, results='asis'}
cNames <- c(paste0(faIcon("calendar-alt", class = "far", title = "Måned")), 
   "<i class=\"fas\" title=\"Total antal\">&#x3A3;</i>",
   paste0(faIcon("mars", title = "Han"),"/",
          faIcon("venus", title = "Hun"), "/",
          faIcon("question", title = "Ukendt"), " (%)"),
   "<span title='Nedre'>N</span>/<span title='Mellem'>M</span>/<span title='Øvre'>Ø</span>/<span title='Vorgod Å'>V</span>/<span title='Omme Å'>O</span>/<span title='Andet'>A</span> (%)",
   "<span title='Nedre'>N</span>/<span title='Mellem'>M</span>/<span title='Øvre'>Ø</span>/<span title='Vorgod Å'>V</span>/<span title='Omme Å'>O</span>/<span title='Andet'>A</span> (%)",
   "<span title='Flue'>F</span>/<span title='Spin'>S</span>/<span title='Orm'>O</span>/<span title='Andet'>A</span> (%)",
   paste0(faIcon("sync", title = "C&R"),"/",
          faIcon("times", title = "Hjemtaget"), " (%)"),
   paste0(faIcon("ruler-horizontal", title="Gens længde"), "/",
          faIcon("ruler", title="Max længde")),
   paste0(faIcon("balance-scale", title="Gens. vægt"), "/",
          faIcon("weight-hanging", title="Max vægt"),
          "/<i class=\"fas\" title=\"Total vægt\">&#x3A3;</i>"),
   paste0(faIcon("heart", title="Gens kondition"), "/",
          faIcon("gratipay", title="Max kondition"))
   ) 

datStatMonthSal %>%
  kable(col.names = cNames, escape = F, align = "c", format = "html") %>%
  kable_styling(fixed_thead = T, font_size = 10,
                bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>% 
  add_header_above(c(" " = 2, "Køn", "Område (alle fangster/hjemtaget)" = 2, "Metode", "Genudsat", "Længde", "Vægt", "Kondition"))
```
