name: Run R script Karup

on: 
  schedule: 
    - cron: '0 * * * *'  # every hour

jobs:
  render:
    name: Run R script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install packages
        run: Rscript install.R
      - name: Run R script
        run: Rscript script_karup.R
      - name: Commit results
        run: |
          git commit --allow-empty -am 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          #git commit 'data/data_karup_catch_seatrout_web.csv' --allow-empty -m 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          #git commit 'data/data_karup_catch_seatrout_2020-.csv' --allow-empty -m 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
