name: R script Skjern 1

on: 
  push:
    paths:
      - .github/run_script_skjern1.yaml
      - script_skjern1.R
  schedule: 
    - cron: '0 * * * *'  # every hour

jobs:
  render:
    name: Run script_skjern1.R
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install packages
        run: Rscript install.R
      - name: Run R script
        run: Rscript script_skjern1.R
      - name: Commit results
        run: |
          git commit --allow-empty -am 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
